// GENERATED by scripts/make-category-icons.mjs -- do not edit by hand.
// Re-run that script after adding or replacing a photo in "all each cat/".

const SLUGS_WITH_ICONS = new Set([
  '3a-quality-cz',
  '4a-quality-cz',
  '5a-quality-cz',
  '7a-quality',
  'ceramic',
  'coloured-cz-stones',
  'crushed-ice-cut',
  'crystal',
  'cz-glass-beads',
  'evil-eye-malachite',
  'flat-polki-foil-polki',
  'foiled-glass-crystal',
  'fusion-stones',
  'glass-pearls',
  'glass-stones',
  'heighted-cz-stones',
  'lab-grown-stones',
  'malachite',
  'mop-mother-of-pearl',
  'mop-onyx',
  'natural-emeralds',
  'queen-conch',
  'rainbow-corundum',
  'ruby-green-cabs',
  'ruby-synthetic',
  'star-light',
  'synthetic-opals',
  'turkey-ring-stones'
]);

/**
 * The little transparent gemstone cut-out shown beside a category's name in
 * every category dropdown, or null for categories whose reference photo the
 * owner hasn't supplied yet -- those fall back to a plain text row.
 */
export function categoryIconUrl(slug: string | null | undefined): string | null {
  if (!slug || !SLUGS_WITH_ICONS.has(slug)) return null;
  return `/reference/categories/${slug}.png`;
}
