BEGIN;
ALTER TABLE public.category_shapes ADD COLUMN IF NOT EXISTS ref_photo_url text;
ALTER TABLE public.category_shape_sizes ADD COLUMN IF NOT EXISTS diamond_equivalent_ct numeric;
CREATE TEMP TABLE moissanite_import(shape_name text,image text,size_mm text,dew numeric) ON COMMIT DROP;
INSERT INTO moissanite_import VALUES
('Round','/moissanite-shapes/round.png','0.7',0.001),
('Round','/moissanite-shapes/round.png','0.8',0.003),
('Round','/moissanite-shapes/round.png','0.9',0.004),
('Round','/moissanite-shapes/round.png','1',0.005),
('Round','/moissanite-shapes/round.png','1.1',0.006),
('Round','/moissanite-shapes/round.png','1.2',0.008),
('Round','/moissanite-shapes/round.png','1.3',0.01),
('Round','/moissanite-shapes/round.png','1.4',0.012),
('Round','/moissanite-shapes/round.png','1.5',0.015),
('Round','/moissanite-shapes/round.png','1.6',0.017),
('Round','/moissanite-shapes/round.png','1.7',0.02),
('Round','/moissanite-shapes/round.png','1.8',0.025),
('Round','/moissanite-shapes/round.png','1.9',0.027),
('Round','/moissanite-shapes/round.png','2',0.03),
('Round','/moissanite-shapes/round.png','2.1',0.035),
('Round','/moissanite-shapes/round.png','2.2',0.04),
('Round','/moissanite-shapes/round.png','2.3',0.045),
('Round','/moissanite-shapes/round.png','2.4',0.05),
('Round','/moissanite-shapes/round.png','2.5',0.06),
('Round','/moissanite-shapes/round.png','2.6',0.065),
('Round','/moissanite-shapes/round.png','2.7',0.07),
('Round','/moissanite-shapes/round.png','2.8',0.08),
('Round','/moissanite-shapes/round.png','2.9',0.085),
('Round','/moissanite-shapes/round.png','3',0.1),
('Round','/moissanite-shapes/round.png','3.25',0.15),
('Round','/moissanite-shapes/round.png','3.5',0.2),
('Round','/moissanite-shapes/round.png','3.6',0.2),
('Round','/moissanite-shapes/round.png','3.75',0.25),
('Round','/moissanite-shapes/round.png','4',0.3),
('Round','/moissanite-shapes/round.png','4.25',0.35),
('Round','/moissanite-shapes/round.png','4.5',0.4),
('Round','/moissanite-shapes/round.png','4.75',0.45),
('Round','/moissanite-shapes/round.png','5',0.5),
('Round','/moissanite-shapes/round.png','5.25',0.55),
('Round','/moissanite-shapes/round.png','5.4',0.6),
('Round','/moissanite-shapes/round.png','5.5',0.6),
('Round','/moissanite-shapes/round.png','5.75',0.7),
('Round','/moissanite-shapes/round.png','6',0.8),
('Round','/moissanite-shapes/round.png','6.25',0.9),
('Round','/moissanite-shapes/round.png','6.3',0.9),
('Round','/moissanite-shapes/round.png','6.5',1.0),
('Round','/moissanite-shapes/round.png','7',1.2),
('Round','/moissanite-shapes/round.png','7.2',1.2),
('Round','/moissanite-shapes/round.png','7.25',1.35),
('Round','/moissanite-shapes/round.png','7.5',1.5),
('Round','/moissanite-shapes/round.png','8',2.0),
('Round','/moissanite-shapes/round.png','8.1',2.0),
('Round','/moissanite-shapes/round.png','8.5',2.5),
('Round','/moissanite-shapes/round.png','9',3.0),
('Round','/moissanite-shapes/round.png','9.5',3.5),
('Round','/moissanite-shapes/round.png','10',4.0),
('Round','/moissanite-shapes/round.png','10.5',4.5),
('Round','/moissanite-shapes/round.png','11',5.0),
('Round','/moissanite-shapes/round.png','11.5',5.5),
('Round','/moissanite-shapes/round.png','12',6.0),
('Round','/moissanite-shapes/round.png','12.5',7.0),
('Round','/moissanite-shapes/round.png','13',8.0),
('Round','/moissanite-shapes/round.png','13.5',9.0),
('Round','/moissanite-shapes/round.png','14',10.0),
('Round','/moissanite-shapes/round.png','14.5',11.0),
('Round','/moissanite-shapes/round.png','15',12.0),
('Round','/moissanite-shapes/round.png','16',15.0),
('Round','/moissanite-shapes/round.png','18',20.0),
('Round','/moissanite-shapes/round.png','20',25.0),
('Round','/moissanite-shapes/round.png','30',100.0),
('Emerald Cut','/moissanite-shapes/emerald.png','2x4',0.2),
('Emerald Cut','/moissanite-shapes/emerald.png','3x4',0.4),
('Emerald Cut','/moissanite-shapes/emerald.png','3x5',0.5),
('Emerald Cut','/moissanite-shapes/emerald.png','4x5',0.7),
('Emerald Cut','/moissanite-shapes/emerald.png','4x6',0.8),
('Emerald Cut','/moissanite-shapes/emerald.png','4.5x6.5',0.9),
('Emerald Cut','/moissanite-shapes/emerald.png','5x7',1.0),
('Emerald Cut','/moissanite-shapes/emerald.png','5x8',1.5),
('Emerald Cut','/moissanite-shapes/emerald.png','6x8',2.0),
('Emerald Cut','/moissanite-shapes/emerald.png','6.5x8.5',2.5),
('Emerald Cut','/moissanite-shapes/emerald.png','7x9',3.0),
('Emerald Cut','/moissanite-shapes/emerald.png','8x10',4.0),
('Emerald Cut','/moissanite-shapes/emerald.png','9x11',5.0),
('Emerald Cut','/moissanite-shapes/emerald.png','10x12',8.0),
('Emerald Cut','/moissanite-shapes/emerald.png','10x14',10.0),
('Emerald Cut','/moissanite-shapes/emerald.png','12x14',12.0),
('Radiant','/moissanite-shapes/radiant.png','2x4',0.2),
('Radiant','/moissanite-shapes/radiant.png','3x4',0.4),
('Radiant','/moissanite-shapes/radiant.png','3x5',0.5),
('Radiant','/moissanite-shapes/radiant.png','4x5',0.7),
('Radiant','/moissanite-shapes/radiant.png','4x6',0.8),
('Radiant','/moissanite-shapes/radiant.png','4.5x6.5',0.9),
('Radiant','/moissanite-shapes/radiant.png','5x7',1.0),
('Radiant','/moissanite-shapes/radiant.png','5x8',1.5),
('Radiant','/moissanite-shapes/radiant.png','6x8',2.0),
('Radiant','/moissanite-shapes/radiant.png','6.5x8.5',2.5),
('Radiant','/moissanite-shapes/radiant.png','7x9',3.0),
('Radiant','/moissanite-shapes/radiant.png','8x10',4.0),
('Radiant','/moissanite-shapes/radiant.png','9x11',5.0),
('Radiant','/moissanite-shapes/radiant.png','10x12',8.0),
('Radiant','/moissanite-shapes/radiant.png','10x14',10.0),
('Radiant','/moissanite-shapes/radiant.png','12x14',12.0),
('Oval','/moissanite-shapes/oval.png','2x4',0.1),
('Oval','/moissanite-shapes/oval.png','3x5',0.3),
('Oval','/moissanite-shapes/oval.png','4x6',0.5),
('Oval','/moissanite-shapes/oval.png','5x7',1.0),
('Oval','/moissanite-shapes/oval.png','6x8',1.5),
('Oval','/moissanite-shapes/oval.png','6.5x8.5',1.75),
('Oval','/moissanite-shapes/oval.png','6x9',1.75),
('Oval','/moissanite-shapes/oval.png','7x9',2.0),
('Oval','/moissanite-shapes/oval.png','7.5x9.5',2.5),
('Oval','/moissanite-shapes/oval.png','7x10',2.5),
('Oval','/moissanite-shapes/oval.png','8x10',3.0),
('Oval','/moissanite-shapes/oval.png','8x12',4.5),
('Oval','/moissanite-shapes/oval.png','9x11',5.0),
('Oval','/moissanite-shapes/oval.png','9x12',5.5),
('Oval','/moissanite-shapes/oval.png','10x12',6.0),
('Oval','/moissanite-shapes/oval.png','10x14',8.0),
('Pear','/moissanite-shapes/pear.png','1.5x3',0.1),
('Pear','/moissanite-shapes/pear.png','2x3',0.12),
('Pear','/moissanite-shapes/pear.png','2.5x3',0.15),
('Pear','/moissanite-shapes/pear.png','2.5x3.5',0.18),
('Pear','/moissanite-shapes/pear.png','2x4',0.18),
('Pear','/moissanite-shapes/pear.png','2.5x4',0.2),
('Pear','/moissanite-shapes/pear.png','3x4',0.3),
('Pear','/moissanite-shapes/pear.png','3x5',0.35),
('Pear','/moissanite-shapes/pear.png','4x6',0.5),
('Pear','/moissanite-shapes/pear.png','5x7',0.8),
('Pear','/moissanite-shapes/pear.png','5x8',1.0),
('Pear','/moissanite-shapes/pear.png','6x8',1.25),
('Pear','/moissanite-shapes/pear.png','6x9',1.5),
('Pear','/moissanite-shapes/pear.png','7x10',2.0),
('Pear','/moissanite-shapes/pear.png','7x10.5',2.5),
('Pear','/moissanite-shapes/pear.png','7x11',3.0),
('Pear','/moissanite-shapes/pear.png','8x10',3.0),
('Pear','/moissanite-shapes/pear.png','8x12',4.0),
('Pear','/moissanite-shapes/pear.png','9x13',5.0),
('Pear','/moissanite-shapes/pear.png','10x12',5.0),
('Pear','/moissanite-shapes/pear.png','10x14',6.0),
('Pear','/moissanite-shapes/pear.png','11x15',8.0),
('Pear','/moissanite-shapes/pear.png','12x14',8.0),
('Pear','/moissanite-shapes/pear.png','12x16',10.0),
('Heart','/moissanite-shapes/heart.png','3x3',0.1),
('Heart','/moissanite-shapes/heart.png','3.5x3.5',0.2),
('Heart','/moissanite-shapes/heart.png','4x4',0.3),
('Heart','/moissanite-shapes/heart.png','4.5x4.5',0.4),
('Heart','/moissanite-shapes/heart.png','5x5',0.5),
('Heart','/moissanite-shapes/heart.png','5.5x5.5',0.6),
('Heart','/moissanite-shapes/heart.png','6x6',0.8),
('Heart','/moissanite-shapes/heart.png','6.5x6.5',1.0),
('Heart','/moissanite-shapes/heart.png','7x7',1.2),
('Heart','/moissanite-shapes/heart.png','7.5x7.5',1.5),
('Heart','/moissanite-shapes/heart.png','8x8',2.0),
('Heart','/moissanite-shapes/heart.png','8.5x8.5',2.5),
('Heart','/moissanite-shapes/heart.png','9x9',3.0),
('Heart','/moissanite-shapes/heart.png','9.5x9.5',3.5),
('Heart','/moissanite-shapes/heart.png','10x10',4.0),
('Heart','/moissanite-shapes/heart.png','11x11',5.0),
('Heart','/moissanite-shapes/heart.png','12x12',6.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','3x5',0.5),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','4x6',0.8),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','5x7',1.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','6x8',2.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','7x9',3.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','8x10',4.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','9x11',5.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','10x12',8.0),
('Cushion Elongated','/moissanite-shapes/long-cushion.png','10x14',10.0),
('Cushion','/moissanite-shapes/cushion.png','3.5x3.5',0.25),
('Cushion','/moissanite-shapes/cushion.png','4x4',0.35),
('Cushion','/moissanite-shapes/cushion.png','4.5x4.5',0.5),
('Cushion','/moissanite-shapes/cushion.png','5x5',0.6),
('Cushion','/moissanite-shapes/cushion.png','5.5x5.5',0.8),
('Cushion','/moissanite-shapes/cushion.png','6x6',1.0),
('Cushion','/moissanite-shapes/cushion.png','6.5x6.5',1.5),
('Cushion','/moissanite-shapes/cushion.png','7x7',2.0),
('Cushion','/moissanite-shapes/cushion.png','7.5x7.5',2.2),
('Cushion','/moissanite-shapes/cushion.png','8x8',2.5),
('Cushion','/moissanite-shapes/cushion.png','8.5x8.5',3.0),
('Cushion','/moissanite-shapes/cushion.png','9x9',3.5),
('Cushion','/moissanite-shapes/cushion.png','9.5x9.5',4.5),
('Cushion','/moissanite-shapes/cushion.png','10x10',5.0),
('Cushion','/moissanite-shapes/cushion.png','10.5x10.5',6.0),
('Cushion','/moissanite-shapes/cushion.png','11x11',7.0),
('Asscher','/moissanite-shapes/asscher.png','3.5x3.5',0.25),
('Asscher','/moissanite-shapes/asscher.png','4x4',0.35),
('Asscher','/moissanite-shapes/asscher.png','4.5x4.5',0.5),
('Asscher','/moissanite-shapes/asscher.png','5x5',0.6),
('Asscher','/moissanite-shapes/asscher.png','5.5x5.5',0.8),
('Asscher','/moissanite-shapes/asscher.png','6x6',1.0),
('Asscher','/moissanite-shapes/asscher.png','6.5x6.5',1.5),
('Asscher','/moissanite-shapes/asscher.png','7x7',2.0),
('Asscher','/moissanite-shapes/asscher.png','7.5x7.5',2.2),
('Asscher','/moissanite-shapes/asscher.png','8x8',2.5),
('Asscher','/moissanite-shapes/asscher.png','8.5x8.5',3.0),
('Asscher','/moissanite-shapes/asscher.png','9x9',3.5),
('Asscher','/moissanite-shapes/asscher.png','9.5x9.5',4.5),
('Asscher','/moissanite-shapes/asscher.png','10x10',5.0),
('Asscher','/moissanite-shapes/asscher.png','10.5x10.5',6.0),
('Asscher','/moissanite-shapes/asscher.png','11x11',7.0),
('Marquise','/moissanite-shapes/marquise.png','1.5x3',0.05),
('Marquise','/moissanite-shapes/marquise.png','2x4',0.1),
('Marquise','/moissanite-shapes/marquise.png','2.5x5',0.2),
('Marquise','/moissanite-shapes/marquise.png','3x6',0.3),
('Marquise','/moissanite-shapes/marquise.png','4x8',0.5),
('Marquise','/moissanite-shapes/marquise.png','4.5x9',0.8),
('Marquise','/moissanite-shapes/marquise.png','5x10',1.0),
('Marquise','/moissanite-shapes/marquise.png','6x12',2.0),
('Marquise','/moissanite-shapes/marquise.png','6x13',2.5),
('Marquise','/moissanite-shapes/marquise.png','7x14',3.0),
('Marquise','/moissanite-shapes/marquise.png','8x16',6.0),
('Princess','/moissanite-shapes/princess.png','1.5x1.5',0.06),
('Princess','/moissanite-shapes/princess.png','2x2',0.08),
('Princess','/moissanite-shapes/princess.png','2.5x2.5',0.15),
('Princess','/moissanite-shapes/princess.png','3x3',0.3),
('Princess','/moissanite-shapes/princess.png','3.5x3.5',0.35),
('Princess','/moissanite-shapes/princess.png','4x4',0.4),
('Princess','/moissanite-shapes/princess.png','4.5x4.5',0.6),
('Princess','/moissanite-shapes/princess.png','5x5',0.8),
('Princess','/moissanite-shapes/princess.png','5.5x5.5',1.0),
('Princess','/moissanite-shapes/princess.png','6x6',1.2),
('Princess','/moissanite-shapes/princess.png','6.5x6.5',1.5),
('Princess','/moissanite-shapes/princess.png','7x7',2.0),
('Princess','/moissanite-shapes/princess.png','7.5x7.5',2.5),
('Princess','/moissanite-shapes/princess.png','8x8',3.0),
('Princess','/moissanite-shapes/princess.png','8.5x8.5',3.5),
('Princess','/moissanite-shapes/princess.png','9x9',4.0),
('Princess','/moissanite-shapes/princess.png','9.5x9.5',5.0),
('Princess','/moissanite-shapes/princess.png','10x10',6.0),
('Princess','/moissanite-shapes/princess.png','11x11',8.0),
('Princess','/moissanite-shapes/princess.png','12x12',10.0),
('Trillion','/moissanite-shapes/trillion.png','4x4',0.3),
('Trillion','/moissanite-shapes/trillion.png','4.5x4.5',0.4),
('Trillion','/moissanite-shapes/trillion.png','5x5',0.5),
('Trillion','/moissanite-shapes/trillion.png','5.5x5.5',0.6),
('Trillion','/moissanite-shapes/trillion.png','6x6',0.8),
('Trillion','/moissanite-shapes/trillion.png','6.5x6.5',1.0),
('Trillion','/moissanite-shapes/trillion.png','7x7',1.2),
('Trillion','/moissanite-shapes/trillion.png','7.5x7.5',1.5),
('Trillion','/moissanite-shapes/trillion.png','8x8',2.0),
('Trillion','/moissanite-shapes/trillion.png','8.5x8.5',2.5),
('Trillion','/moissanite-shapes/trillion.png','9x9',3.0),
('Trillion','/moissanite-shapes/trillion.png','9.5x9.5',3.5),
('Trillion','/moissanite-shapes/trillion.png','10x10',4.0),
('Trillion','/moissanite-shapes/trillion.png','11x11',5.0),
('Triangle','/moissanite-shapes/triangle.png','4x4',0.3),
('Triangle','/moissanite-shapes/triangle.png','4.5x4.5',0.4),
('Triangle','/moissanite-shapes/triangle.png','5x5',0.5),
('Triangle','/moissanite-shapes/triangle.png','5.5x5.5',0.6),
('Triangle','/moissanite-shapes/triangle.png','6x6',0.8),
('Triangle','/moissanite-shapes/triangle.png','6.5x6.5',1.0),
('Triangle','/moissanite-shapes/triangle.png','7x7',1.2),
('Triangle','/moissanite-shapes/triangle.png','7.5x7.5',1.5),
('Triangle','/moissanite-shapes/triangle.png','8x8',2.0),
('Triangle','/moissanite-shapes/triangle.png','8.5x8.5',2.5),
('Triangle','/moissanite-shapes/triangle.png','9x9',3.0),
('Triangle','/moissanite-shapes/triangle.png','9.5x9.5',3.5),
('Triangle','/moissanite-shapes/triangle.png','10x10',4.0),
('Triangle','/moissanite-shapes/triangle.png','11x11',5.0),
('Trapezoid','/moissanite-shapes/trapezoid.png','2x1.5x1',0.06),
('Trapezoid','/moissanite-shapes/trapezoid.png','2.5x1.5x1',0.07),
('Trapezoid','/moissanite-shapes/trapezoid.png','3x1.5x1',0.08),
('Trapezoid','/moissanite-shapes/trapezoid.png','3x2x1',0.1),
('Trapezoid','/moissanite-shapes/trapezoid.png','4x3x2',0.2),
('Trapezoid','/moissanite-shapes/trapezoid.png','5x3x2',0.3),
('Trapezoid','/moissanite-shapes/trapezoid.png','5x4x2',0.4),
('Baguette','/moissanite-shapes/baguette.png','1x1.5',0.04),
('Baguette','/moissanite-shapes/baguette.png','1x2',0.06),
('Baguette','/moissanite-shapes/baguette.png','1.5x2',0.07),
('Baguette','/moissanite-shapes/baguette.png','1.5x2.5',0.075),
('Baguette','/moissanite-shapes/baguette.png','1.5x3',0.09),
('Baguette','/moissanite-shapes/baguette.png','2x3',0.12),
('Baguette','/moissanite-shapes/baguette.png','2x4',0.15),
('Baguette','/moissanite-shapes/baguette.png','2.5x5',0.25),
('Baguette','/moissanite-shapes/baguette.png','3x5',0.5),
('Baguette','/moissanite-shapes/baguette.png','3x6',0.65);
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM categories WHERE id=34 AND slug='moissanite') THEN RAISE EXCEPTION 'Moissanite category mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM moissanite_import i WHERE NOT EXISTS(SELECT 1 FROM shapes s WHERE s.name=i.shape_name)) THEN RAISE EXCEPTION 'Missing master shape'; END IF;
END $$;
INSERT INTO shape_sizes(shape_id,size_mm)
SELECT DISTINCT s.id,i.size_mm FROM moissanite_import i JOIN shapes s ON s.name=i.shape_name
WHERE NOT EXISTS(SELECT 1 FROM shape_sizes z WHERE z.shape_id=s.id AND z.size_mm=i.size_mm);
INSERT INTO colors(name,hex_value) SELECT 'White (DEF)','#ffffff' WHERE NOT EXISTS(SELECT 1 FROM colors WHERE name='White (DEF)');
DELETE FROM category_shape_sizes WHERE category_id=34;
DELETE FROM category_shapes WHERE category_id=34;
DELETE FROM category_colors WHERE category_id=34;
DELETE FROM shape_size_prices WHERE category_id=34;
INSERT INTO category_shapes(category_id,shape_id,ref_photo_url)
SELECT DISTINCT 34,s.id,i.image FROM moissanite_import i JOIN shapes s ON s.name=i.shape_name;
INSERT INTO category_shape_sizes(category_id,shape_size_id,diamond_equivalent_ct)
SELECT 34,(SELECT min(z.id) FROM shape_sizes z WHERE z.shape_id=s.id AND z.size_mm=i.size_mm),i.dew
FROM moissanite_import i JOIN shapes s ON s.name=i.shape_name;
INSERT INTO category_colors(category_id,color_id) SELECT 34,min(id) FROM colors WHERE name='White (DEF)';
COMMIT;
