-- Materials: the level above categories ("Ruby" over Ruby Corundum, Ruby
-- Chatham, Ruby Foil Pota...). Many-to-many, so a category can sit under more
-- than one material. Colours, shapes and sizes stay linked to categories
-- (category_colors / category_shapes / category_shape_sizes); a material's
-- colours and sizes are whatever its categories carry.
BEGIN;
CREATE TABLE IF NOT EXISTS public.materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) > 0),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS materials_name_key ON public.materials (lower(btrim(name)));

CREATE TABLE IF NOT EXISTS public.material_categories (
  material_id integer NOT NULL REFERENCES public.materials(id) ON DELETE CASCADE,
  category_id integer NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (material_id, category_id)
);
CREATE INDEX IF NOT EXISTS material_categories_category_idx ON public.material_categories (category_id);

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.material_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS materials_public_read ON public.materials;
CREATE POLICY materials_public_read ON public.materials FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS material_categories_public_read ON public.material_categories;
CREATE POLICY material_categories_public_read ON public.material_categories FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.materials, public.material_categories TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.materials, public.material_categories FROM anon, authenticated;
GRANT ALL ON public.materials, public.material_categories TO service_role;
COMMIT;
